[package]
name = "fee-flag-calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.1"
clap = { version = "4.4.6", features = ["derive"] }
grrs = "0.1.0"
